nodes:
  ouster:
    display_name: Ouster 3D Lidar
    ros_node_name: /a300_00008/os_driver
    launch_command: ros2 launch ouster_ros driver.launch.py

  realsense:
    display_name: RealSense D435
    ros_node_name: /a300_00008/camera/camera
    launch_command: ros2 launch realsense2_camera rs_launch.py

  joystick:
    display_name: Legion Joystick
    ros_node_name: /joy_node
    launch_command: ros2 launch legion_joystick husky_joy.launch.py

recording:
  output_dir: ~/rosbags

  topics:
    - /a300_00008/tf
    - /a300_00008/tf_static
    - /a300_00008/cmd_vel
    - /a300_00008/platform/odom
    - /a300_00008/sensors/lidar3d_0/points
    - /a300_00008/camera/color/image_raw
    - /a300_00008/camera/depth/image_rect_raw
    - /a300_00008/camera/color/camera_info